export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES';
export const GET_VIDEOGAME_DETAIL = 'GET_VIDEOGAME_DETAIL';
export const GET_VIDEOGAME_BY_NAME = 'GET_VIDEOGAME_BY_NAME';

export const GET_ALL_GENRES = 'GET_ALL_GENRES';

export const CLEAR_DETAIL = 'CLEAR_DETAIL';
export const CLEAR_VIDEOGAMES = 'CLEAR_VIDEOGAMES';
export const CLEAR_GENRES = 'CLEAR_GENRES';

export const APPLY_FILTERS = 'APPLY_FILTERS';

export const CREATE_VIDEOGAME = 'CREATE_VIDEOGAME';