export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES';
export const GET_VIDEOGAME_DETAIL = 'GET_VIDEOGAME_DETAIL';
export const GET_VIDEOGAME_BY_NAME = 'GET_VIDEOGAME_BY_NAME';

export const GET_ALL_GENRES = 'GET_ALL_GENRES';

export const CLEAR_DETAIL = 'CLEAR_DETAIL';
export const CLEAR_VIDEOGAMES = 'CLEAR_VIDEOGAMES';
export const CLEAR_GENRES = 'CLEAR_GENRES';

export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
export const FILTER_BY_ORIGIN =  'FILTER_BY_ORIGIN';
export const FILTER_BY_DIRECTION =  'FILTER_BY_DIRECTION';
export const FILTER_BY_ALPHABETIC =  'FILTER_BY_ALPHABETIC';
export const FILTER_BY_RATING =  'FILTER_BY_RATING';

export const CREATE_VIDEOGAME = 'CREATE_VIDEOGAME';